/**
 * 本文件由 hvigorfile.ts 自动生成，勿手改。
 * debug 构建：内容来自项目根目录 .env，仅供开发期快捷登录使用。
 */
export class DevConfig {
  static readonly isDev: boolean = true;
  static readonly lanServer: string = 'http://192.168.50.4:13000';
  static readonly lanUsername: string = 'DongShu';
  static readonly lanPassword: string = 'P4pyMK2FQZoWomu';
  static readonly wanServer: string = 'https://mc.dongshu.fun:99';
  static readonly wanUsername: string = 'DongShu';
  static readonly wanPassword: string = 'P4pyMK2FQZoWomu';
}
