#!/usr/bin/env python3
"""Generate the Xcode project using the committed dependency lock.

After deliberately changing project.yml, use --update-lock to resolve dependencies
and refresh Package.resolved. Normal builds never refresh dependency versions.
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOCK = ROOT / "Package.resolved"
PROJECT_LOCK = (
    ROOT / "MovieClaw.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved"
)
METADATA = ROOT / "Shared/About/AetherEngineDependency.generated.swift"


def engine_dependency(spec):
    dependency = spec["packages"]["AetherEngine"]
    revision = dependency.get("revision", "")
    if not re.fullmatch(r"[0-9a-f]{40}", revision):
        raise ValueError("AetherEngine must use a full commit SHA, not a branch or version range")
    url = dependency["url"]
    if not url.startswith("https://github.com/"):
        raise ValueError("AetherEngine must use a GitHub HTTPS source URL")
    return url, revision


def check_lock(spec, lock):
    url, revision = engine_dependency(spec)
    pins = {pin["identity"]: pin for pin in lock["pins"]}
    engine = pins.get("aetherengine")
    if (
        not engine
        or engine["location"].removesuffix(".git") != url.removesuffix(".git")
        or engine["state"]["revision"] != revision
    ):
        raise ValueError(
            "AetherEngine pin differs from Package.resolved; "
            "deliberately refresh with --update-lock"
        )
    for pin in pins.values():
        if not re.fullmatch(r"[0-9a-f]{40}", pin["state"].get("revision", "")):
            raise ValueError(f"Unpinned dependency: {pin['identity']}")
    ffmpeg = pins.get("ffmpegbuild")
    if (
        not ffmpeg
        or ffmpeg["state"].get("version") != spec["packages"]["FFmpegBuild"]["exactVersion"]
    ):
        raise ValueError("FFmpegBuild version differs from project.yml")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--update-lock", action="store_true")
    args = parser.parse_args()
    spec = json.loads(subprocess.check_output(["xcodegen", "dump", "--type", "json"], cwd=ROOT))
    url, revision = engine_dependency(spec)
    if not args.update_lock:
        check_lock(spec, json.loads(LOCK.read_text()))
    source_url = url.removesuffix(".git") + "/tree/" + revision
    metadata = (
        "// Generated by scripts/prepare-project.py; do not edit.\n"
        "enum AetherEngineDependency {\n"
        f"    static let sourceURL = {json.dumps(source_url)}\n"
        "}\n"
    )
    if not METADATA.exists() or METADATA.read_text() != metadata:
        METADATA.write_text(metadata)
    subprocess.run(["xcodegen", "generate", "--quiet"], cwd=ROOT, check=True)
    PROJECT_LOCK.parent.mkdir(parents=True, exist_ok=True)
    if LOCK.exists():
        shutil.copyfile(LOCK, PROJECT_LOCK)
    if args.update_lock:
        cache = os.environ.get("MC_SPM", str(Path.home() / "workspace/.mc-ios-spm"))
        subprocess.run(
            [
                "xcodebuild",
                "-resolvePackageDependencies",
                "-project",
                "MovieClaw.xcodeproj",
                "-scheme",
                "MovieClaw",
                "-clonedSourcePackagesDirPath",
                cache,
                "-packageAuthorizationProvider",
                "netrc",
            ],
            cwd=ROOT,
            check=True,
        )
        check_lock(spec, json.loads(PROJECT_LOCK.read_text()))
        shutil.copyfile(PROJECT_LOCK, LOCK)
    print(f"AetherEngine pinned: {revision}")


if __name__ == "__main__":
    try:
        main()
    except (ValueError, KeyError, OSError, subprocess.CalledProcessError) as error:
        print(f"Dependency preparation failed: {error}", file=sys.stderr)
        sys.exit(1)
